## multidimensional array object

In [2]:
import numpy as np
from pandas import read_pickle

In [3]:
train_data = read_pickle('../data/cleaned_train_data.pkl')
train_data

mssubclass mszoning  lotfrontage  ...  saletype salecondition saleprice
id                                      ...                                  
1             60       RL         65.0  ...        WD        Normal    208500
2             20       RL         80.0  ...        WD        Normal    181500
3             60       RL         68.0  ...        WD        Normal    223500
4             70       RL         60.0  ...        WD       Abnorml    140000
5             60       RL         84.0  ...        WD        Normal    250000
...          ...      ...          ...  ...       ...           ...       ...
1456          60       RL         62.0  ...        WD        Normal    175000
1457          20       RL         85.0  ...        WD        Normal    210000
1458          70       RL         66.0  ...        WD        Normal    266500
1459          20       RL         68.0  ...        WD        Normal    142125
1460          20       RL         75.0  ...        WD        Normal    147500

[1460 rows x 76 columns]

In [4]:
data = np.asarray(train_data)
data

array([[60, 'RL', 65.0, ..., 'WD', 'Normal', 208500],
       [20, 'RL', 80.0, ..., 'WD', 'Normal', 181500],
       [60, 'RL', 68.0, ..., 'WD', 'Normal', 223500],
       ...,
       [70, 'RL', 66.0, ..., 'WD', 'Normal', 266500],
       [20, 'RL', 68.0, ..., 'WD', 'Normal', 142125],
       [20, 'RL', 75.0, ..., 'WD', 'Normal', 147500]], dtype=object)

***shape***

In [5]:
data.shape

(1460, 76)

In [8]:
data.ndim

2

In [9]:
data.dtype

dtype('O')

***creating ndarrays***

In [6]:
a_array = np.array(np.random.randint(0, 100, 20))
a_array

array([31, 47,  4, 33, 30, 33,  2, 27,  3, 75, 42, 80, 17, 41, 59, 33, 95,
       10,  0, 11])

In [7]:
a_array = np.array([np.random.randint(100, 500, 12), np.random.randint(0, 100, 12)])
a_array

array([[108, 385, 475, 265, 310, 113, 395, 486, 286, 494, 395, 294],
       [ 65,  72,  71,  48,  53,  43,  84,  52,  38,  64,  93,  53]])

***special arrays***

In [13]:
np.zeros(10), np.ones(10), np.ones((2, 5)), np.zeros((2, 5)), np.eye(4), np.identity(4)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

***meta data***

In [14]:
np.array(np.random.randint(10, 50, 10), float), np.array(np.random.randint(50, 100, 10), int)

(array([25., 47., 31., 46., 23., 31., 31., 16., 38., 21.]),
 array([63, 88, 60, 68, 51, 80, 58, 70, 53, 89]))