## multidimensional array object

In [84]:
import numpy as np
from pandas import read_pickle
from numpy import linalg

In [3]:
train_data = read_pickle('../data/cleaned_train_data.pkl')
train_data

mssubclass mszoning  lotfrontage  ...  saletype salecondition saleprice
id                                      ...                                  
1             60       RL         65.0  ...        WD        Normal    208500
2             20       RL         80.0  ...        WD        Normal    181500
3             60       RL         68.0  ...        WD        Normal    223500
4             70       RL         60.0  ...        WD       Abnorml    140000
5             60       RL         84.0  ...        WD        Normal    250000
...          ...      ...          ...  ...       ...           ...       ...
1456          60       RL         62.0  ...        WD        Normal    175000
1457          20       RL         85.0  ...        WD        Normal    210000
1458          70       RL         66.0  ...        WD        Normal    266500
1459          20       RL         68.0  ...        WD        Normal    142125
1460          20       RL         75.0  ...        WD        Normal    147500

[1460 rows x 76 columns]

In [4]:
data = np.asarray(train_data)
data

array([[60, 'RL', 65.0, ..., 'WD', 'Normal', 208500],
       [20, 'RL', 80.0, ..., 'WD', 'Normal', 181500],
       [60, 'RL', 68.0, ..., 'WD', 'Normal', 223500],
       ...,
       [70, 'RL', 66.0, ..., 'WD', 'Normal', 266500],
       [20, 'RL', 68.0, ..., 'WD', 'Normal', 142125],
       [20, 'RL', 75.0, ..., 'WD', 'Normal', 147500]], dtype=object)

***shape***

In [5]:
data.shape

(1460, 76)

In [8]:
data.ndim

2

In [9]:
data.dtype

dtype('O')

***creating ndarrays***

In [6]:
a_array = np.array(np.random.randint(0, 100, 20))
a_array

array([31, 47,  4, 33, 30, 33,  2, 27,  3, 75, 42, 80, 17, 41, 59, 33, 95,
       10,  0, 11])

In [7]:
a_array = np.array([np.random.randint(100, 500, 12), np.random.randint(0, 100, 12)])
a_array

array([[108, 385, 475, 265, 310, 113, 395, 486, 286, 494, 395, 294],
       [ 65,  72,  71,  48,  53,  43,  84,  52,  38,  64,  93,  53]])

***special arrays***

In [13]:
np.zeros(10), np.ones(10), np.ones((2, 5)), np.zeros((2, 5)), np.eye(4), np.identity(4)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

***meta data***

In [14]:
np.array(np.random.randint(10, 50, 10), float), np.array(np.random.randint(50, 100, 10), int)

(array([25., 47., 31., 46., 23., 31., 31., 16., 38., 21.]),
 array([63, 88, 60, 68, 51, 80, 58, 70, 53, 89]))

## indexing and slicing

In [15]:
data[:]

array([[60, 'RL', 65.0, ..., 'WD', 'Normal', 208500],
       [20, 'RL', 80.0, ..., 'WD', 'Normal', 181500],
       [60, 'RL', 68.0, ..., 'WD', 'Normal', 223500],
       ...,
       [70, 'RL', 66.0, ..., 'WD', 'Normal', 266500],
       [20, 'RL', 68.0, ..., 'WD', 'Normal', 142125],
       [20, 'RL', 75.0, ..., 'WD', 'Normal', 147500]], dtype=object)

In [16]:
data[6]

array([20, 'RL', 75.0, 10084, 'Pave', 'Reg', 'Lvl', 'AllPub', 'Inside',
       'Gtl', 'Somerst', 'Norm', 'Norm', '1Fam', '1Story', 8, 5, 2004,
       2005, 'Gable', 'CompShg', 'VinylSd', 'VinylSd', 'Stone', 186.0,
       'Gd', 'TA', 'PConc', 'Ex', 'TA', 'Av', 'GLQ', 1369, 'Unf', 0, 317,
       1686, 'GasA', 'Ex', 'Y', 'SBrkr', 1694, 0, 0, 1694, 1, 0, 2, 0, 3,
       1, 'Gd', 7, 'Typ', 1, 'Gd', 'Attchd', 2004.0, 'RFn', 2, 636, 'TA',
       'TA', 'Y', 255, 57, 0, 0, 0, 0, 0, 8, 2007, 'WD', 'Normal', 307000],
      dtype=object)

In [17]:
data[6, 1]

'RL'

In [19]:
test_3rd_array = data.copy().reshape((73, 76, 20))
test_3rd_array

array([[[60, 'RL', 65.0, ..., 2003, 2003, 'Gable'],
        ['CompShg', 'VinylSd', 'VinylSd', ..., 'GasA', 'Ex', 'Y'],
        ['SBrkr', 856, 854, ..., 2003.0, 'RFn', 2],
        ...,
        [6, 1958, 1965, ..., 'Unf', 0, 525],
        [1029, 'GasA', 'TA', ..., 'Min1', 0, 'None'],
        ['Attchd', 1958.0, 'Unf', ..., 'COD', 'Abnorml', 139000]],

       [[60, 'RL', 101.0, ..., 2005, 2006, 'Gable'],
        ['CompShg', 'VinylSd', 'VinylSd', ..., 'GasA', 'Ex', 'Y'],
        ['SBrkr', 1158, 1218, ..., 2005.0, 'RFn', 3],
        ...,
        [5, 1955, 1955, ..., 'None', 0, 0],
        [0, 'GasA', 'TA', ..., 'Typ', 0, 'None'],
        ['None', 0.0, 'None', ..., 'WD', 'AdjLand', 82000]],

       [[20, 'RL', 84.0, ..., 1965, 1965, 'Gable'],
        ['CompShg', 'Wd Sdng', 'Wd Sdng', ..., 'GasA', 'Ex', 'Y'],
        ['SBrkr', 1324, 0, ..., 1965.0, 'RFn', 2],
        ...,
        [7, 1972, 1972, ..., 'Unf', 0, 148],
        [780, 'GasA', 'Ex', ..., 'Typ', 0, 'None'],
        ['Detchd', 1973.0,

In [22]:
test_3rd_array.shape, test_3rd_array[10].shape

((73, 76, 20), (76, 20))

In [23]:
test_3rd_array[10, 10]

array([0, 2, 1, 'TA', 6, 'Min1', 0, 'None', 'Attchd', 1924.0, 'Unf', 1,
       398, 'TA', 'TA', 'Y', 0, 0, 126, 0], dtype=object)

In [24]:
test_3rd_array[10, 10, 10]

'Unf'

In [26]:
data[:2], test_3rd_array[:2]

(array([[60, 'RL', 65.0, 8450, 'Pave', 'Reg', 'Lvl', 'AllPub', 'Inside',
         'Gtl', 'CollgCr', 'Norm', 'Norm', '1Fam', '2Story', 7, 5, 2003,
         2003, 'Gable', 'CompShg', 'VinylSd', 'VinylSd', 'BrkFace', 196.0,
         'Gd', 'TA', 'PConc', 'Gd', 'TA', 'No', 'GLQ', 706, 'Unf', 0, 150,
         856, 'GasA', 'Ex', 'Y', 'SBrkr', 856, 854, 0, 1710, 1, 0, 2, 1,
         3, 1, 'Gd', 8, 'Typ', 0, 'None', 'Attchd', 2003.0, 'RFn', 2, 548,
         'TA', 'TA', 'Y', 0, 61, 0, 0, 0, 0, 0, 2, 2008, 'WD', 'Normal',
         208500],
        [20, 'RL', 80.0, 9600, 'Pave', 'Reg', 'Lvl', 'AllPub', 'FR2',
         'Gtl', 'Veenker', 'Feedr', 'Norm', '1Fam', '1Story', 6, 8, 1976,
         1976, 'Gable', 'CompShg', 'MetalSd', 'MetalSd', 'None', 0.0,
         'TA', 'TA', 'CBlock', 'Gd', 'TA', 'Gd', 'ALQ', 978, 'Unf', 0,
         284, 1262, 'GasA', 'Ex', 'Y', 'SBrkr', 1262, 0, 0, 1262, 0, 1, 2,
         0, 3, 1, 'TA', 6, 'Typ', 1, 'TA', 'Attchd', 1976.0, 'RFn', 2,
         460, 'TA', 'TA', 'Y', 298

In [27]:
data[:2, 1]

array(['RL', 'RL'], dtype=object)

In [29]:
data[1, :2]

array([20, 'RL'], dtype=object)

In [28]:
data[:2, :2]

array([[60, 'RL'],
       [20, 'RL']], dtype=object)

In [30]:
data[:, 2]

array([65.0, 80.0, 68.0, ..., 66.0, 68.0, 75.0], dtype=object)

In [31]:
test_3rd_array[:2, :2, :2]

array([[[60, 'RL'],
        ['CompShg', 'VinylSd']],

       [[60, 'RL'],
        ['CompShg', 'VinylSd']]], dtype=object)

***fancy indexing***

In [42]:
test_nd = data.copy()[data[:, 1] != 'RL'] = 12
test_nd

12

In [43]:
array_index = {np.random.randint(0, 1460) for i in range(10)}
data[list(array_index)]

array([[20, 'RL', 67.0, 9808, 'Pave', 'IR1', 'Lvl', 'AllPub', 'Inside',
        'Gtl', 'CollgCr', 'Norm', 'Norm', '1Fam', '1Story', 7, 5, 2002,
        2002, 'Gable', 'CompShg', 'VinylSd', 'VinylSd', 'BrkFace', 110.0,
        'Gd', 'TA', 'PConc', 'Gd', 'TA', 'No', 'GLQ', 788, 'Unf', 0, 785,
        1573, 'GasA', 'Ex', 'Y', 'SBrkr', 1573, 0, 0, 1573, 1, 0, 2, 0,
        3, 1, 'Gd', 6, 'Typ', 0, 'None', 'Attchd', 2002.0, 'RFn', 2, 544,
        'TA', 'TA', 'Y', 0, 72, 0, 0, 0, 0, 0, 3, 2009, 'WD', 'Normal',
        227000],
       [60, 'RL', 108.0, 13418, 'Pave', 'Reg', 'Lvl', 'AllPub', 'Inside',
        'Gtl', 'NridgHt', 'Norm', 'Norm', '1Fam', '2Story', 8, 5, 2004,
        2005, 'Gable', 'CompShg', 'VinylSd', 'VinylSd', 'Stone', 132.0,
        'Gd', 'TA', 'PConc', 'Ex', 'TA', 'Av', 'Unf', 0, 'Unf', 0, 1117,
        1117, 'GasA', 'Ex', 'Y', 'SBrkr', 1132, 1320, 0, 2452, 0, 0, 3,
        1, 4, 1, 'Gd', 9, 'Typ', 1, 'Gd', 'BuiltIn', 2004.0, 'Fin', 3,
        691, 'TA', 'TA', 'Y', 113, 32, 

## transposing arrays and swapping axes

In [44]:
data.shape, data.T.shape

((1460, 76), (76, 1460))

In [45]:
test_3rd_array.shape, test_3rd_array.swapaxes(1, 2).shape

((73, 76, 20), (73, 20, 76))

## universal functions

***basic math***

In [50]:
np.abs(data[:, -1] - np.max(data[:, -1]))

array([546500, 573500, 531500, ..., 488500, 612875, 607500], dtype=object)

In [60]:
price = np.asarray(data[:, -1], float)
price

array([208500., 181500., 223500., ..., 266500., 142125., 147500.])

In [63]:
np.sqrt(price), np.square(price), np.exp(price)

c:\users\ashen\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.


(array([456.61800227, 426.02816808, 472.75786614, ..., 516.23637997,
        376.99469492, 384.05728739]),
 array([4.34722500e+10, 3.29422500e+10, 4.99522500e+10, ...,
        7.10222500e+10, 2.01995156e+10, 2.17562500e+10]),
 array([inf, inf, inf, ..., inf, inf, inf]))

In [64]:
np.log(price), np.log2(price), np.log10(price), np.log1p(price)

(array([12.24769432, 12.10901093, 12.31716669, ..., 12.49312952,
        11.86446223, 11.90158345]),
 array([17.66968786, 17.46961002, 17.76991531, ..., 18.02377601,
        17.11680082, 17.17035543]),
 array([5.31910606, 5.25887663, 5.34927753, ..., 5.42569721, 5.15267048,
        5.16879202]),
 array([12.24769912, 12.10901644, 12.31717117, ..., 12.49313327,
        11.86446927, 11.90159023]))

***rounding***

In [65]:
np.sign(np.log(price)), np.ceil(np.log(price)), np.floor(np.log(price)), np.rint(np.log(price)), np.modf(np.log(price))

(array([1., 1., 1., ..., 1., 1., 1.]),
 array([13., 13., 13., ..., 13., 12., 12.]),
 array([12., 12., 12., ..., 12., 11., 11.]),
 array([12., 12., 12., ..., 12., 12., 12.]),
 (array([0.24769432, 0.10901093, 0.31716669, ..., 0.49312952, 0.86446223,
         0.90158345]),
  array([12., 12., 12., ..., 12., 11., 11.])))

***checkers***

In [66]:
np.isnan(np.log(price)), np.isfinite(np.log(price)), np.isinf(np.log(price))

(array([False, False, False, ..., False, False, False]),
 array([ True,  True,  True, ...,  True,  True,  True]),
 array([False, False, False, ..., False, False, False]))

***trigonometry***

In [70]:
np.sin(price), np.cos(price), np.tan(np.log1p(price)), np.sinh(np.log1p(price)), np.cosh(
    np.log1p(price)), np.tanh(np.log1p(price))

(array([-0.93952251, -0.69442763,  0.72802616, ..., -0.96483213,
        -0.60649785,  0.79358512]),
 array([ 0.34248716, -0.71956255,  0.68554935, ...,  0.2628668 ,
         0.79508513, -0.60845925]),
 array([-0.32991566, -0.49215778, -0.25448935, ..., -0.07336856,
        -0.84554386, -0.78379328]),
 array([104250.4999976 ,  90750.49999725, 111750.49999776, ...,
        133250.49999812,  71062.99999648,  73750.49999661]),
 array([104250.5000024 ,  90750.50000275, 111750.50000224, ...,
        133250.50000188,  71063.00000352,  73750.50000339]),
 array([1., 1., 1., ..., 1., 1., 1.]))

***inverse trigonometric***

In [72]:
np.arcsin(np.log(price)), np.arccos(np.log(price)), np.arctan(np.log(price))

c:\users\ashen\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arcsin
  """Entry point for launching an IPython kernel.
c:\users\ashen\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arccos
  """Entry point for launching an IPython kernel.


(array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([1.48932902, 1.48840017, 1.4897865 , ..., 1.49092263, 1.48670975,
        1.48697079]))

## array oriented programming with arrays

In [74]:
x, y = np.meshgrid(price, np.log1p(price))
x.shape, y.shape

((1460, 1460), (1460, 1460))

In [75]:
np.sqrt(x ** 2 + y ** 2)

array([[208500.00035973, 181500.00041324, 223500.00033558, ...,
        266500.00028144, 142125.00052773, 147500.0005085 ],
       [208500.00035163, 181500.00040393, 223500.00032803, ...,
        266500.0002751 , 142125.00051584, 147500.00049705],
       [208500.00036382, 181500.00041794, 223500.0003394 , ...,
        266500.00028464, 142125.00053373, 147500.00051428],
       ...,
       [208500.00037429, 181500.00042997, 223500.00034917, ...,
        266500.00029283, 142125.00054909, 147500.00052908],
       [208500.00033757, 181500.00038778, 223500.00031491, ...,
        266500.0002641 , 142125.00049522, 147500.00047717],
       [208500.00033968, 181500.00039021, 223500.00031689, ...,
        266500.00026576, 142125.00049832, 147500.00048016]])

In [76]:
area = data[:, 3]
np.where(area > 10000, 0.11, 11.01)

array([11.01, 11.01,  0.11, ..., 11.01, 11.01, 11.01])

## matrix manipulation

In [78]:
a_matrix = np.random.randint(1, 100, 16).reshape((4, 4))
b_matrix = np.random.randint(100, 200, 16).reshape((4, 4))

np.dot(a_matrix, b_matrix)

array([[21141, 22452, 19818, 21248],
       [35252, 28291, 33452, 31290],
       [ 7164,  6237,  6598,  6487],
       [32594, 31152, 27274, 29395]])

In [81]:
X = np.random.randn(5, 5)

mat = np.dot(X, X.T)
mat

array([[10.36279855, -2.16690712,  1.12038711, -2.27177195, -0.0180921 ],
       [-2.16690712,  7.66387622,  3.79209449,  6.33339324, -1.9756655 ],
       [ 1.12038711,  3.79209449,  7.65524017,  2.02055696, -1.60712169],
       [-2.27177195,  6.33339324,  2.02055696,  5.59237309, -1.67083045],
       [-0.0180921 , -1.9756655 , -1.60712169, -1.67083045,  0.78136314]])

In [82]:
linalg.inv(mat)

array([[   0.3458904 ,   -4.17509837,    1.55663983,    5.84663145,
           5.15522085],
       [  -4.17509837,   81.12004399,  -29.8376515 , -110.39962684,
         -92.42982537],
       [   1.55663983,  -29.8376515 ,   11.27616603,   40.84249265,
          35.12066797],
       [   5.84663145, -110.39962684,   40.84249265,  151.095769  ,
         128.09320731],
       [   5.15522085,  -92.42982537,   35.12066797,  128.09320731,
         113.83704308]])

In [83]:
linalg.qr(mat)

(array([[-0.95195972, -0.21175935,  0.21790328,  0.02775511,  0.02604775],
        [ 0.199059  , -0.67170785,  0.2093572 ,  0.49723876, -0.46701955],
        [-0.10292233, -0.42269028, -0.88271021,  0.00852597,  0.17745396],
        [ 0.20869222, -0.53527837,  0.35872081, -0.34979406,  0.64721567],
        [ 0.001662  ,  0.19691758,  0.02880594,  0.79344483,  0.57518365]]),
 array([[-1.08857532e+01,  4.51652692e+00, -6.80604571e-01,
          4.37970167e+00, -5.58033018e-01],
        [ 0.00000000e+00, -1.00710761e+01, -7.41825864e+00,
         -7.94968303e+00,  3.05843946e+00],
        [ 0.00000000e+00,  0.00000000e+00, -5.04079921e+00,
          1.00531940e+00,  4.24206861e-01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         -1.78508086e-01,  2.07833210e-01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  5.05269314e-03]]))

In [85]:
np.diag(mat), np.trace(mat)

(array([10.36279855,  7.66387622,  7.65524017,  5.59237309,  0.78136314]),
 32.05565117140973)

In [87]:
linalg.det(mat), linalg.eig(mat), linalg.pinv(mat), linalg.svd(mat)

(0.4984419402442112,
 (array([1.67453617e+01, 1.07302854e+01, 4.35227643e+00, 2.24893611e-01,
         2.83410010e-03]),
  array([[-0.34396916,  0.84482006,  0.40754092,  0.03502207, -0.02545867],
         [ 0.65038458,  0.11601192,  0.29523461,  0.49975457,  0.47604939],
         [ 0.37840617,  0.51099351, -0.7511287 ,  0.0017106 , -0.17747438],
         [ 0.53402934,  0.00555431,  0.42641563, -0.32593934, -0.65323431],
         [-0.17408775, -0.10805134, -0.02687579,  0.80173527, -0.56081781]])),
 array([[   0.3458904 ,   -4.17509837,    1.55663983,    5.84663145,
            5.15522085],
        [  -4.17509837,   81.12004399,  -29.8376515 , -110.39962684,
          -92.42982537],
        [   1.55663983,  -29.8376515 ,   11.27616603,   40.84249265,
           35.12066797],
        [   5.84663145, -110.39962684,   40.84249265,  151.095769  ,
          128.09320731],
        [   5.15522085,  -92.42982537,   35.12066797,  128.09320731,
          113.83704308]]),
 (array([[-0.34396916, -