## multidimensional array object

In [2]:
import numpy as np
from pandas import read_pickle

In [3]:
train_data = read_pickle('../data/cleaned_train_data.pkl')
train_data

mssubclass mszoning  lotfrontage  ...  saletype salecondition saleprice
id                                      ...                                  
1             60       RL         65.0  ...        WD        Normal    208500
2             20       RL         80.0  ...        WD        Normal    181500
3             60       RL         68.0  ...        WD        Normal    223500
4             70       RL         60.0  ...        WD       Abnorml    140000
5             60       RL         84.0  ...        WD        Normal    250000
...          ...      ...          ...  ...       ...           ...       ...
1456          60       RL         62.0  ...        WD        Normal    175000
1457          20       RL         85.0  ...        WD        Normal    210000
1458          70       RL         66.0  ...        WD        Normal    266500
1459          20       RL         68.0  ...        WD        Normal    142125
1460          20       RL         75.0  ...        WD        Normal    147500

[1460 rows x 76 columns]

In [4]:
data = np.asarray(train_data)
data

array([[60, 'RL', 65.0, ..., 'WD', 'Normal', 208500],
       [20, 'RL', 80.0, ..., 'WD', 'Normal', 181500],
       [60, 'RL', 68.0, ..., 'WD', 'Normal', 223500],
       ...,
       [70, 'RL', 66.0, ..., 'WD', 'Normal', 266500],
       [20, 'RL', 68.0, ..., 'WD', 'Normal', 142125],
       [20, 'RL', 75.0, ..., 'WD', 'Normal', 147500]], dtype=object)

***shape***

In [5]:
data.shape

(1460, 76)

In [8]:
data.ndim

2

In [9]:
data.dtype

dtype('O')

***creating ndarrays***

In [6]:
a_array = np.array(np.random.randint(0, 100, 20))
a_array

array([31, 47,  4, 33, 30, 33,  2, 27,  3, 75, 42, 80, 17, 41, 59, 33, 95,
       10,  0, 11])

In [7]:
a_array = np.array([np.random.randint(100, 500, 12), np.random.randint(0, 100, 12)])
a_array

array([[108, 385, 475, 265, 310, 113, 395, 486, 286, 494, 395, 294],
       [ 65,  72,  71,  48,  53,  43,  84,  52,  38,  64,  93,  53]])

***special arrays***

In [13]:
np.zeros(10), np.ones(10), np.ones((2, 5)), np.zeros((2, 5)), np.eye(4), np.identity(4)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

***meta data***

In [14]:
np.array(np.random.randint(10, 50, 10), float), np.array(np.random.randint(50, 100, 10), int)

(array([25., 47., 31., 46., 23., 31., 31., 16., 38., 21.]),
 array([63, 88, 60, 68, 51, 80, 58, 70, 53, 89]))

## indexing and slicing

In [15]:
data[:]

array([[60, 'RL', 65.0, ..., 'WD', 'Normal', 208500],
       [20, 'RL', 80.0, ..., 'WD', 'Normal', 181500],
       [60, 'RL', 68.0, ..., 'WD', 'Normal', 223500],
       ...,
       [70, 'RL', 66.0, ..., 'WD', 'Normal', 266500],
       [20, 'RL', 68.0, ..., 'WD', 'Normal', 142125],
       [20, 'RL', 75.0, ..., 'WD', 'Normal', 147500]], dtype=object)

In [16]:
data[6]

array([20, 'RL', 75.0, 10084, 'Pave', 'Reg', 'Lvl', 'AllPub', 'Inside',
       'Gtl', 'Somerst', 'Norm', 'Norm', '1Fam', '1Story', 8, 5, 2004,
       2005, 'Gable', 'CompShg', 'VinylSd', 'VinylSd', 'Stone', 186.0,
       'Gd', 'TA', 'PConc', 'Ex', 'TA', 'Av', 'GLQ', 1369, 'Unf', 0, 317,
       1686, 'GasA', 'Ex', 'Y', 'SBrkr', 1694, 0, 0, 1694, 1, 0, 2, 0, 3,
       1, 'Gd', 7, 'Typ', 1, 'Gd', 'Attchd', 2004.0, 'RFn', 2, 636, 'TA',
       'TA', 'Y', 255, 57, 0, 0, 0, 0, 0, 8, 2007, 'WD', 'Normal', 307000],
      dtype=object)

In [17]:
data[6, 1]

'RL'

In [19]:
test_3rd_array = data.copy().reshape((73, 76, 20))
test_3rd_array

array([[[60, 'RL', 65.0, ..., 2003, 2003, 'Gable'],
        ['CompShg', 'VinylSd', 'VinylSd', ..., 'GasA', 'Ex', 'Y'],
        ['SBrkr', 856, 854, ..., 2003.0, 'RFn', 2],
        ...,
        [6, 1958, 1965, ..., 'Unf', 0, 525],
        [1029, 'GasA', 'TA', ..., 'Min1', 0, 'None'],
        ['Attchd', 1958.0, 'Unf', ..., 'COD', 'Abnorml', 139000]],

       [[60, 'RL', 101.0, ..., 2005, 2006, 'Gable'],
        ['CompShg', 'VinylSd', 'VinylSd', ..., 'GasA', 'Ex', 'Y'],
        ['SBrkr', 1158, 1218, ..., 2005.0, 'RFn', 3],
        ...,
        [5, 1955, 1955, ..., 'None', 0, 0],
        [0, 'GasA', 'TA', ..., 'Typ', 0, 'None'],
        ['None', 0.0, 'None', ..., 'WD', 'AdjLand', 82000]],

       [[20, 'RL', 84.0, ..., 1965, 1965, 'Gable'],
        ['CompShg', 'Wd Sdng', 'Wd Sdng', ..., 'GasA', 'Ex', 'Y'],
        ['SBrkr', 1324, 0, ..., 1965.0, 'RFn', 2],
        ...,
        [7, 1972, 1972, ..., 'Unf', 0, 148],
        [780, 'GasA', 'Ex', ..., 'Typ', 0, 'None'],
        ['Detchd', 1973.0,

In [22]:
test_3rd_array.shape, test_3rd_array[10].shape

((73, 76, 20), (76, 20))

In [23]:
test_3rd_array[10, 10]

array([0, 2, 1, 'TA', 6, 'Min1', 0, 'None', 'Attchd', 1924.0, 'Unf', 1,
       398, 'TA', 'TA', 'Y', 0, 0, 126, 0], dtype=object)

In [24]:
test_3rd_array[10, 10, 10]

'Unf'

In [26]:
data[:2], test_3rd_array[:2]

(array([[60, 'RL', 65.0, 8450, 'Pave', 'Reg', 'Lvl', 'AllPub', 'Inside',
         'Gtl', 'CollgCr', 'Norm', 'Norm', '1Fam', '2Story', 7, 5, 2003,
         2003, 'Gable', 'CompShg', 'VinylSd', 'VinylSd', 'BrkFace', 196.0,
         'Gd', 'TA', 'PConc', 'Gd', 'TA', 'No', 'GLQ', 706, 'Unf', 0, 150,
         856, 'GasA', 'Ex', 'Y', 'SBrkr', 856, 854, 0, 1710, 1, 0, 2, 1,
         3, 1, 'Gd', 8, 'Typ', 0, 'None', 'Attchd', 2003.0, 'RFn', 2, 548,
         'TA', 'TA', 'Y', 0, 61, 0, 0, 0, 0, 0, 2, 2008, 'WD', 'Normal',
         208500],
        [20, 'RL', 80.0, 9600, 'Pave', 'Reg', 'Lvl', 'AllPub', 'FR2',
         'Gtl', 'Veenker', 'Feedr', 'Norm', '1Fam', '1Story', 6, 8, 1976,
         1976, 'Gable', 'CompShg', 'MetalSd', 'MetalSd', 'None', 0.0,
         'TA', 'TA', 'CBlock', 'Gd', 'TA', 'Gd', 'ALQ', 978, 'Unf', 0,
         284, 1262, 'GasA', 'Ex', 'Y', 'SBrkr', 1262, 0, 0, 1262, 0, 1, 2,
         0, 3, 1, 'TA', 6, 'Typ', 1, 'TA', 'Attchd', 1976.0, 'RFn', 2,
         460, 'TA', 'TA', 'Y', 298

In [27]:
data[:2, 1]

array(['RL', 'RL'], dtype=object)

In [29]:
data[1, :2]

array([20, 'RL'], dtype=object)

In [28]:
data[:2, :2]

array([[60, 'RL'],
       [20, 'RL']], dtype=object)

In [30]:
data[:, 2]

array([65.0, 80.0, 68.0, ..., 66.0, 68.0, 75.0], dtype=object)

In [31]:
test_3rd_array[:2, :2, :2]

array([[[60, 'RL'],
        ['CompShg', 'VinylSd']],

       [[60, 'RL'],
        ['CompShg', 'VinylSd']]], dtype=object)

***fancy indexing***

In [42]:
test_nd = data.copy()[data[:, 1] != 'RL'] = 12
test_nd

12

In [43]:
array_index = {np.random.randint(0, 1460) for i in range(10)}
data[list(array_index)]

array([[20, 'RL', 67.0, 9808, 'Pave', 'IR1', 'Lvl', 'AllPub', 'Inside',
        'Gtl', 'CollgCr', 'Norm', 'Norm', '1Fam', '1Story', 7, 5, 2002,
        2002, 'Gable', 'CompShg', 'VinylSd', 'VinylSd', 'BrkFace', 110.0,
        'Gd', 'TA', 'PConc', 'Gd', 'TA', 'No', 'GLQ', 788, 'Unf', 0, 785,
        1573, 'GasA', 'Ex', 'Y', 'SBrkr', 1573, 0, 0, 1573, 1, 0, 2, 0,
        3, 1, 'Gd', 6, 'Typ', 0, 'None', 'Attchd', 2002.0, 'RFn', 2, 544,
        'TA', 'TA', 'Y', 0, 72, 0, 0, 0, 0, 0, 3, 2009, 'WD', 'Normal',
        227000],
       [60, 'RL', 108.0, 13418, 'Pave', 'Reg', 'Lvl', 'AllPub', 'Inside',
        'Gtl', 'NridgHt', 'Norm', 'Norm', '1Fam', '2Story', 8, 5, 2004,
        2005, 'Gable', 'CompShg', 'VinylSd', 'VinylSd', 'Stone', 132.0,
        'Gd', 'TA', 'PConc', 'Ex', 'TA', 'Av', 'Unf', 0, 'Unf', 0, 1117,
        1117, 'GasA', 'Ex', 'Y', 'SBrkr', 1132, 1320, 0, 2452, 0, 0, 3,
        1, 4, 1, 'Gd', 9, 'Typ', 1, 'Gd', 'BuiltIn', 2004.0, 'Fin', 3,
        691, 'TA', 'TA', 'Y', 113, 32, 

## transposing arrays and swapping axes

In [44]:
data.shape, data.T.shape

((1460, 76), (76, 1460))

In [45]:
test_3rd_array.shape, test_3rd_array.swapaxes(1,2).shape

((73, 76, 20), (73, 20, 76))